name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: Preconfiguration
      run: |
        mkdir -p logs
        sudo apt-get update
        sudo apt-get install -y bsdmainutils
    - name: Build with Maven
      run: |
        cd roman-numbers
        mvn -B install --file pom.xml | tee ../logs/build.log
    - name: Static Analysis
      run: |
        cd roman-numbers
        mvn checkstyle:checkstyle | tee ../logs/checkstyle.log
    - name: Code Coverage
      run: |
        cd roman-numbers
        mvn jacoco:report
    - name: Upload Result on README.md
      run: |
        
        sed -i 's/\[INFO\] //g' logs/build.log
        sed -i 's/\[INFO\] //g' logs/checkstyle.log
        
        echo "# Build Results" > README.md
        echo "" >> README.md
        lineNum=$(grep -n -m 1 "T E S T S" "logs/build.log" | cut -d: -f1)
        endLineNum=$(grep -n -m 1 "Results:" "logs/build.log" | cut -d: -f1)
        awk -v start="$lineNum" -v end="$endLineNum" 'NR>=start-1 && NR<=end+2' "logs/build.log" >> "README.md"
        lineNum=$(grep -n -m 1 "BUILD" "logs/build.log" | cut -d: -f1)
        awk -v n="$lineNum" 'NR>=n-1' "logs/build.log" >> "README.md"
        echo "" >> README.md
        
        echo "" >> README.md
        echo "# Checkstyle Results" >> README.md
        echo "" >> README.md
        lineNum=$(grep -n -m 1 "Starting audit..." "logs/checkstyle.log" | cut -d: -f1)
        awk -v n="$lineNum" 'NR>=n' "logs/checkstyle.log" >> "README.md"
        echo "" >> README.md
        
        echo "" >> README.md
        echo "# Code Coverage Results" >> README.md
        echo "" >> README.md
        echo "| GROUP | PACKAGE | CLASS | INSTRUCTION_MISSED | INSTRUCTION_COVERED |" >> README.md
        echo "| ----- | ------- | ----- | ------------------ | ------------------ |" >> README.md
        awk -F',' 'NR>1 {printf("| %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5)}' roman-numbers/target/site/jacoco/jacoco.csv >> README.md
    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git add README.md
        git commit -m "Update README.md"
        git push https://${{ secrets.PAT_ACCESS }}@github.com/faccuzz/Roman_MTSS2.git HEAD:main
        
