name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
    - name: Build with Maven and update README.md
      run: |
        #Report Build
        echo "# Report Build" > README.md
        mvn -B install --file roman-numbers/pom.xml | tee -a README.md
        #Report Analisi Statica
        echo "\n# Report Analisi Statica" >> README.md
        mvn checkstyle:checkstyle | tee -a README.md
        #Report Code Coverage
        echo "\n# Report Code Coverage" >> README.md
        mvn jacoco:report | tee -a README.md
    - name: Commit Changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: "Build and update README.md"
        add: README.md
        push: true