name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
    - name: Build with Maven and update README.md
      run: |
        cd roman-numbers
        #Report Build
        echo "# Report Build" > README.md
        mvn -B install --file pom.xml | tee -a README.md
        #Report Analisi Statica
        echo "\n# Report Analisi Statica" >> README.md
        mvn checkstyle:checkstyle | tee -a README.md
        cd ..
        #Report Code Coverage
        echo "\n# Report Code Coverage" >> README.md
        mvn jacoco:report | tee -a README.md
    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git add README.md
        git commit -m "Build and update README.md"
        git push https://${{ secrets.PAT_ACCESS }}@github.com/faccuzz/Roman_MTSS2.git HEAD:main